name: Deploy GH Pages

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy-gh-pages:
    runs-on: ubuntu-24.04
    steps:
      - name: Deploy GH Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
